version: '4.0'

services:
  tech-hub-server:
#    image: murilosbarbosa/tech-hub-server:mocked  # Use the pre-built image
    build: .  # Build the image from the Dockerfile in the current directory
    network_mode: "host"  # If you want to use the host network. This is not recommended for production, but it's useful for development
    ports:
      - "8080:8080"  # Map port 8080 of the container to port 8080 of the host
    environment:
      # Define the environment variables
      DB_HOST: "localhost"
      DB_PORT: "3306"
      DB_NAME: "techhub"
      DB_USER: "root"
      DB_PASSWORD: "root"
      EMAIL_SENDER_REMETENTE: "teste@gmail.com"
      EMAIL_SENDER_PASSWORD: "123"
      EMAIL_SENDER_CRON: "0 0 0 * * 5"
      EMAIL_SENDER_API_KEY: "123"
      USE_CURRENT_CONTEXT_PATH_IN_IMAGE_URL:  false
