name: CD with Self-Hosted Runner

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker compose pull

      - name: Stop Docker containers
        run: docker compose down

      - name: Start Docker containers
        run: docker compose up -d
