name: CD with Self-Hosted Runner

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy by BASH file
        run: bash deploy-server.bash
